#!/bin/bash
set -e

# Create directories
mkdir -p src/app/\(auth\)/login
mkdir -p src/app/\(auth\)/register
mkdir -p src/app/\(dashboard\)/dashboard
mkdir -p src/app/\(dashboard\)/projects/\[id\]
mkdir -p src/app/\(dashboard\)/tickets
mkdir -p src/app/\(dashboard\)/users
mkdir -p src/app/\(dashboard\)/settings

mkdir -p src/features/auth/components src/features/auth/hooks src/features/auth/services
mkdir -p src/features/dashboard/components src/features/dashboard/hooks src/features/dashboard/services
mkdir -p src/features/projects/components src/features/projects/hooks src/features/projects/services
mkdir -p src/features/tickets/components src/features/tickets/hooks src/features/tickets/services
mkdir -p src/features/users/components src/features/users/hooks src/features/users/services
mkdir -p src/features/settings/components src/features/settings/services

mkdir -p src/components/ui src/components/DataTable src/components/Modal src/components/RoleGuard src/components/ProtectedRoute src/components/Badge src/components/EmptyState

mkdir -p src/lib/supabase src/lib/api src/lib/utils src/lib/constants

mkdir -p src/store

mkdir -p src/types

mkdir -p src/styles

# Move globals.css
if [ -f app/globals.css ]; then
  mv app/globals.css src/styles/globals.css
fi

# Create files within features
touch src/features/auth/authSlice.ts src/features/auth/types.ts
touch src/features/projects/types.ts
touch src/features/tickets/types.ts
touch src/features/users/types.ts

# Create files within lib
touch src/lib/supabase/client.ts src/lib/supabase/server.ts
touch src/lib/api/apiClient.ts src/lib/api/queryClient.ts

# Create files within store
touch src/store/store.ts src/store/rootReducer.ts

# Create files within types
touch src/types/global.ts src/types/api.ts

# Generate basic skeleton for Page components
function create_page() {
  echo "export default function Page() { return <div>$1</div>; }" > "$2"
}

create_page "Login Page" src/app/\(auth\)/login/page.tsx
create_page "Register Page" src/app/\(auth\)/register/page.tsx
create_page "Dashboard Page" src/app/\(dashboard\)/dashboard/page.tsx
create_page "Projects Page" src/app/\(dashboard\)/projects/page.tsx
create_page "Project Details Page" src/app/\(dashboard\)/projects/\[id\]/page.tsx
create_page "Tickets Page" src/app/\(dashboard\)/tickets/page.tsx
create_page "Users Page" src/app/\(dashboard\)/users/page.tsx
create_page "Settings Page" src/app/\(dashboard\)/settings/page.tsx

# Generate basic layouts
cat << 'LAYOUT_EOF' > src/app/\(auth\)/layout.tsx
export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return <div className="auth-layout">{children}</div>;
}
LAYOUT_EOF

cat << 'LAYOUT_EOF' > src/app/\(dashboard\)/layout.tsx
export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return <div className="dashboard-layout">{children}</div>;
}
LAYOUT_EOF

# Setup Root Layout
if [ -f app/layout.tsx ]; then
  # modify import "./globals.css" to import "../styles/globals.css"
  sed 's|import "./globals.css"|import "../styles/globals.css"|g' app/layout.tsx > src/app/layout.tsx
  rm -rf app
else
  cat << 'LAYOUT_EOF' > src/app/layout.tsx
import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Opsboard App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
LAYOUT_EOF
fi

chmod +x setup.sh
./setup.sh
rm setup.sh
